# Generated by Django 2.1.7 on 2019-02-12 15:42

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('goods_id', models.CharField(max_length=32, verbose_name='商品编号')),
                ('goods_price', models.FloatField(verbose_name='商品价格')),
                ('goods_nprice', models.FloatField(verbose_name='商品现价')),
                ('goods_num', models.IntegerField(verbose_name='商品数量')),
                ('goods_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品简介')),
                ('goods_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品详情')),
                ('goods_time', models.DateField(verbose_name='上架时间')),
                ('goods_picture', models.ImageField(upload_to='images', verbose_name='商品图片')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tag', models.CharField(max_length=32, verbose_name='类型名称')),
                ('type_parent_id', models.IntegerField(verbose_name='父类型')),
                ('type_description', models.TextField(verbose_name='类型描述')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_tag', models.CharField(max_length=32, verbose_name='图片名称')),
                ('picture_src', models.CharField(max_length=32, verbose_name='图片地址')),
                ('picture_dec', models.TextField(verbose_name='图片描述')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Goods', verbose_name='对应商品')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=32, verbose_name='卖家用户名')),
                ('seller_password', models.CharField(max_length=32, verbose_name='卖家密码')),
                ('seller_nickname', models.CharField(max_length=32, verbose_name='卖家昵称')),
                ('seller_phone', models.CharField(max_length=32, verbose_name='卖家电话')),
                ('seller_photo', models.ImageField(upload_to='images', verbose_name='卖家头像')),
                ('seller_email', models.EmailField(max_length=254, verbose_name='卖家邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=32, verbose_name='店铺名称')),
                ('store_address', models.TextField(verbose_name='店铺地址')),
                ('store_logo', models.ImageField(upload_to='images', verbose_name='店铺logo')),
                ('seller_id', models.IntegerField(verbose_name='卖家')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.GoodsType', verbose_name='对应类型'),
        ),
        migrations.AddField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Store', verbose_name='对应店铺'),
        ),
    ]
